# Bluetooth Configuration

CONFIG_BT_DIS_PNP_VID=0x045e
CONFIG_BT_DIS_PNP_PID=0x028e
CONFIG_BT_DEVICE_NAME="Slimbox Xbox BT"
CONFIG_BT_DEVICE_APPEARANCE=961

# Other settings

# (Keep all other settings the same)