- name: Build firmware
  run: |
    python3 -m pip install --upgrade pip
    python3 -m pip install pyelftools

    # verify install (important)
    python3 -c "import elftools; print('elftools OK')"

    ./build.py builds.json > build.sh
    chmod +x build.sh
    ./build.sh
