name: Build Slimbox Firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools ninja-build cmake gperf ccache dfu-util device-tree-compiler wget git

      - name: Install west
        run: pip3 install west

      - name: Initialize west
        run: |
          west init -l .
          west update

      - name: Export Zephyr env
        run: |
          west zephyr-export

      - name: Build firmware (Feather nRF52840)
        run: |
          west build -b feather_nrf52840 app --pristine

      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: slimbox-nicenano-v2
          path: build/zephyr/*.uf2
